[package]
name = "gb_rs_cpu"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gb_rs_asm = { path = "../asm" }
gb_rs_common = { "path" = "../common" }
gb_rs_memory = { "path" = "../memory" }
