[package]
name = "gb_rs_asm_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = ["derive"] }
gb_rs_asm = { path = "../asm" }
clap-num = "1.0"
